shallow_clone: true

environment:
  matrix:
  - LUA: "lua=5.4"

build_script:
  - set PATH=C:\Python27\Scripts;%PATH%
  - pip install codecov
  - pip install hererocks
  - hererocks lua_install --%LUA%
  - call lua_install\bin\activate
  - git clone https://github.com/mpeterv/luacheck

test_script:
  - lua -e 'package.path="luacheck/src/?.lua;luacheck/src/?/init.lua;"..package.path' luacheck/bin/luacheck.lua src spec

after_test:
  - luacov
  - codecov -f luacov.report.out -X gcov
