shallow_clone: true

environment:
  matrix:
  - LUA: "lua=5.1"
  - LUA: "lua=5.2"
  - LUA: "lua=5.3"
  - LUA: "luajit=2.0"
  - LUA: "luajit=2.1"

before_build:
  - set PATH=C:\Python27\Scripts;%PATH%
  - pip install codecov
  - pip install hererocks
  - hererocks lua_install --%LUA% -r latest
  - call lua_install\bin\activate
  - luarocks install busted
  - luarocks install cluacov
  - luarocks install luacheck

build_script:
  - luarocks make

test_script:
  - luacheck .
  - busted -c

after_test:
  - luacov
  - codecov
